### ISSUE TITLE
BUGS

### ISSUE THREAD

**Issue by GlazerMann** [SNL-WaterPower/SNL-SWAN#5]
Element zero is being accessed in this array because of indexing to k-1.

SwanBpntlist.ftn90:    allocate(blistot(nbptot))

I believe that this might be the solution, but it might require special code instead:

SwanBpntlist.ftn90:    allocate(blistot(0:nbptot))

—————————————————

I believe that this line needs added:

SwanCompUnstruc.f90:    !$omp private(kteta) &

Because KTETA is written and read by different threads and is specific to the work being done.

—————————————————

This !$omp master section in SwanCompUnstruc.ftn90 needs an !$omp barrier before it

```
   inocnt = 0
   !
   !$omp master
   inocnv = 0
   !
   islmin = 9999
```

Because shared variables are reset in it.

**Comment by kmruehl** [comment]
@GlazerMann Thanks for your comments. Since these are functions from the baseline SWAN code (which is maintained by TU Delft), and not ones modified by the Sandia team, I recommend:
- checking the latest release of [SWAN v41.10](http://swanmodel.sourceforge.net/) and seeing if these issues have been addressed
- posting your bugs to the SWAN list-serve or [TU Delft maintained](https://sourceforge.net/p/swanmodel/bugs/) bug page.

-Kelley
